name: First Workflow
on: 
  push:
  #workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello github Action
        run: echo "hello this is first workflow in github action"
      - name: by github Action
        run: echo "by this is first workflow in github action"
